cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
language: java
jdk:
- oraclejdk8
install:
- true
branches:
  except:
  - "/^v\\d/"
script:
- "./gradlew build -s && ./gradlew ciPerformRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_1148b47197a9_key -iv $encrypted_1148b47197a9_iv
  -in .travis/github_deploy_key.enc -out .travis/github_deploy_key -d
env:
  global:
  - secure: T5Zi9sMpqsAk/maof3+CsG8zqoQiyihr8fUlTH+DRv4xCoXWDVuZSAc8CYnGZ1rotImBTQc7ttkUX//OPfL+KYEqzk3WE06atc1MBbnoDpmw/isgIy7+9DNRGPX5INgyjk99XkaXf0LpIvowIzzVCrq3m9OtRg4qI8CBsRc7dWKNcWqFaL2js218cxHV+kTlOX6R06gP5JqWoyhrf78PfhIfUzZEvdFHQ0UyeI94HQjftmwwAmn5xIJOhyYSJ7NvxAL774JrodOZoPXy339twwpl3vGjDVGNpkTHxbhe8rHgKzV2bJ+MkWiA9E0r56etrDbDnBsUAS2Bc7iFE30S9tlwZ/8lt4DaE8pKXANgiKBsWs5YLj/TqYShAw0Cz73tllZxYIDNJ9uZXNEtWxgvZVT5tADKHOiGp5u4+lDEZdGixL/9+EKdz34QasQfNYhX5xGOV9gjw4lspjFyqI9NQkxrEswdPVEq43L1tgGCFgKknka8pYYvgd7Luu9Nt77ROJqtyO2T0cPE6DZuir0HkCfuEjv/+8dInoouNTp99I/h5Mz3Jo1pOoQhy9ffyQdeOC0rn9D3cvgf7XyZlbluH54lv/fh2MjlMLAnuLANsqIc6zheyZgzAlLinFYS9uYp9wOAcSzA2ASexZ17542oObOxzFXm7JFFTK8c3lESmpM=
  - secure: cbjJBxIFoDlSMOv+phO8VBb5HxJJbWdMmpKxlB7GslEgYWwg+dsHOpuDVnjz84FNqDUQ9NcYCGF1KB75kxi0jHEJvvFnwhF5KBtQqzRMiYkJaiQY6nB2WvkJLa2Dn6CT8gpYI/Ipz2UDkuUFWU3PEwAEd6adJlRQJYrNX+CWnxmdlQvOiJCraYCFpd/JOWFu5QbgxGCI/BCOyUIfjPXZPzTlYolh9iyXO3r6CZ7srmQ7tv1Qdjl76QgPa/sf/TlaE2WamBTpP3SHDV6ysLWRKqfys3fnPiXQEzHMSFEf5FHd47yAwP8Q/pEMovhJ+Ogodez/oA/a9HWD5mF87DinoGwwEKrGFrLseJfghCcIJ0QKl9BISvwIDAG+4mWPHo8BJ3XrfsodJs2JLioptAovQ5YUfV49ryL0vXsoIDKNCCf1zC9cXfmT5i6VsF4GIKqTvJ5sB1wYQE/htkd1qG12Q0bOWuy27YyQjUGeKMpabq5znbineyvZzYvrZAvN5TifhNnYamO48B6UrlgyhxqlT6PtHn3GX79W3/672phiaB49ku7wSvDLEqJ3drKqtGSb2PUfHwX0Xi8Q4+jbECweRCCAY+BuDhi9/j67maU8JPQxwDGG03uvoJ1Wgu1N49o4F9ho1RKKvNRJy68PgtMIdYXbFCumzjlzQejXamH0SUo=
  - secure: UHxeJUhDwQExS7BY+4MgyXrUsR3qEAYx0y/+COOG53vApzL3aLmmtWk4y76W6oDAjNV08WLCIo4JB9LetfEIJQBZZRSvk4ti7KP2pZjdwdm/nPUEXSPKBePWJ8wZtGmXFUvVOHQVdsY09+cHUcEOXTBHxGwdgQMkrl2a1jKie2M1d8MRjKncgjwQQT1dTVEQSx8+82EYvP5668Ju/3+FdS7Yhx8RIUfMtis+btdDlh87rD07g6bsBAHnUlnVjL+NlM1IUucrObMcLQrlmci/dM3LFt/E6UAwc4aV8dk2oaO1yqRhYrWQla7lQMvth2dJrzmBY+V5h1ur3kTvgWXUueDODbbAhVE+0+7zVy5mgQgV9oroqfs2ILkMJp8eAuq67aliXRwHhNIWhlV9m8zkezQlYviSEIbYof2a/+ftwyI954arJu4OvZTMUi7I0xPzkSJFPmNYDNpOLP26qpBVl5UYWDfRvq45Y4dxNkw8rgSC2N5MuRxrFOEz1MHjstqA6Q88ZovgH419c/kicVlalzkxpiXejPWjIGWKXsXJPw9SwZxbQHcqura2ZTC9jjFQIPPMsbAMuWoBJp5hEhQb78jecEoxNr5CI/kiUnxUtFrJWrqQGVNa9iZkEwClfB9YtcXlJ+ytA66j5mHyMNsR98k+gZr2wAOFlt5NCFYQHkM=
