package _Root.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with uuid = 'JdkGradlePlugins_HttpsGithubComBreskebyJdkGradlePluginsGit_release' (id = 'JdkGradlePlugins_HttpsGithubComBreskebyJdkGradlePluginsGit_release')
accordingly and delete the patch script.
*/
changeVcsRoot("JdkGradlePlugins_HttpsGithubComBreskebyJdkGradlePluginsGit_release") {
    val expected = GitVcsRoot({
        uuid = "JdkGradlePlugins_HttpsGithubComBreskebyJdkGradlePluginsGit_release"
        id = "JdkGradlePlugins_HttpsGithubComBreskebyJdkGradlePluginsGit_release"
        name = "https://github.com/breskeby/jdk-gradle-plugins.git#release"
        url = "https://github.com/breskeby/jdk-gradle-plugins.git"
        branch = "release"
        authMethod = password {
            userName = "breskeby"
            password = "credentialsJSON:9fa99455-2385-48cf-a16a-9a176def2127"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branch = "refs/heads/release"
        branchSpec = "+:refs/heads/release"
        authMethod = password {
        }
    }

}
