package JdkGradlePlugins.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '39a450f0-cdf6-465e-a9bc-5109d30ba798-release' (id = 'JdkGradlePlugins_release_buildAndTest_SanityCheck')
accordingly and delete the patch script.
*/
changeBuildType("39a450f0-cdf6-465e-a9bc-5109d30ba798-release") {
    expectSteps {
        gradle {
            tasks = "clean assemble"
            buildFile = ""
            useGradleWrapper = true
        }
    }
    steps {
        update<GradleBuildStep>(0) {
        }
    }
}
