package JdkGradlePlugins.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.VcsTrigger
import jetbrains.buildServer.configs.kotlin.v2017_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'C8937837-F200-4C21-8AD5-7C5484BC93AB_release' (id = 'JdkGradlePlugins_STAGE_BT_TRIGGER_release')
accordingly and delete the patch script.
*/
changeBuildType("C8937837-F200-4C21-8AD5-7C5484BC93AB_release") {
    triggers {
        val trigger1 = find<VcsTrigger> {
            vcs {
                triggerRules = "+:release"
                branchFilter = "+:release"
            }
        }
        trigger1.apply {
            triggerRules = ""
            branchFilter = "+:*"
            perCheckinTriggering = true
            groupCheckinsByCommitter = true
            enableQueueOptimization = false
        }
    }
}
